version: '3.8'

services: 
  web: 
    build: ./SimbirHealth  
    volumes:
      - ./SimbirHealth:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_HOST=web
      - DJANGO_PORT=8000
    networks:
      - webnet

  db:  
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

volumes:
  postgres_data:

networks: 
  webnet: